"""init

Revision ID: c875c5e29e0c
Revises: 
Create Date: 2022-01-20 13:44:18.322745

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c875c5e29e0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ci_type_group',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项类型分组ID'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='配置项类型分组编码'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='配置项类型分组名称'),
    sa.Column('is_built_in', sa.Boolean(), nullable=False, comment='是否是内置的配置项类型分组?'),
    sa.Column('order', sa.BigInteger(), nullable=False, comment='配置项类型分组排序'),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项类型分组'
    )
    op.create_index(op.f('ix_ci_type_group_code'), 'ci_type_group', ['code'], unique=True)
    op.create_table('relation',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='关系类型ID'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='关系类型编码'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='关系类型名称'),
    sa.Column('is_built_in', sa.Boolean(), nullable=False, comment='是否是内置的关系类型?'),
    sa.Column('source_to_target_desc', sa.String(length=64), nullable=False, comment='源头到目标关系类型描述'),
    sa.Column('target_to_source_desc', sa.String(length=64), nullable=False, comment='目标到源头关系类型描述'),
    sa.Column('direction', sa.Enum('STOT', 'TTOS', 'BOTH', 'NONE', name='relationdirection'), nullable=False, comment='关系方向'),
    sa.PrimaryKeyConstraint('id'),
    comment='关系'
    )
    op.create_index(op.f('ix_relation_code'), 'relation', ['code'], unique=True)
    op.create_table('ci_type',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项类型ID'),
    sa.Column('code', sa.String(length=32), nullable=True, comment='配置项类型编码'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='配置项类型名称'),
    sa.Column('order', sa.BigInteger(), nullable=False, comment='配置项类型排序'),
    sa.Column('is_built_in', sa.Boolean(), nullable=False, comment='是否是内置的配置项类型?'),
    sa.Column('is_disabled', sa.Boolean(), nullable=False, comment='是否是停用的配置项类型?'),
    sa.Column('is_not_show', sa.Boolean(), nullable=False, comment='是否要不显示配置项类型?'),
    sa.Column('icon', sa.String(length=32), nullable=False, comment='配置项类型图标'),
    sa.Column('desc', sa.Text(), nullable=False, comment='配置项类型描述'),
    sa.Column('ci_type_group_id', sa.BigInteger(), nullable=False, comment='配置项类型分组ID'),
    sa.ForeignKeyConstraint(['ci_type_group_id'], ['ci_type_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项类型'
    )
    op.create_index(op.f('ix_ci_type_code'), 'ci_type', ['code'], unique=True)
    op.create_table('ci',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项ID'),
    sa.Column('ci_type_id', sa.BigInteger(), nullable=False, comment='配置项类型ID'),
    sa.ForeignKeyConstraint(['ci_type_id'], ['ci_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项'
    )
    op.create_table('ci_type_attribute_group',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项类型属性分组ID'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='配置项类型属性分组编码'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='配置项类型属性分组名称'),
    sa.Column('order', sa.BigInteger(), nullable=False, comment='配置项类型属性分组排序'),
    sa.Column('is_collapse', sa.Boolean(), nullable=False, comment='配置项类型属性分组是否折叠'),
    sa.Column('ci_type_id', sa.BigInteger(), nullable=False, comment='配置项类型ID'),
    sa.ForeignKeyConstraint(['ci_type_id'], ['ci_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci_type_id', 'code'),
    sa.UniqueConstraint('ci_type_id', 'name'),
    comment='配置项类型属性分组'
    )
    op.create_index(op.f('ix_ci_type_attribute_group_code'), 'ci_type_attribute_group', ['code'], unique=False)
    op.create_table('ci_type_ci_types',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项类型与配置项关联类型关联ID'),
    sa.Column('constraint', sa.Enum('MTOM', 'OTOM', 'OTOO', name='configitemtypeconfigitemtypesconstraint'), nullable=False, comment='来源到目标的约束'),
    sa.Column('desc', sa.Text(), nullable=False, comment='配置项类型与配置项类型关联关联描述'),
    sa.Column('ci_type_source_id', sa.BigInteger(), nullable=False, comment='来源配置项类型ID'),
    sa.Column('ci_type_relation_id', sa.BigInteger(), nullable=True, comment='配置项类型与配置项类型关联关系ID'),
    sa.Column('ci_type_target_id', sa.BigInteger(), nullable=False, comment='目标配置项类型ID'),
    sa.ForeignKeyConstraint(['ci_type_relation_id'], ['relation.id'], ),
    sa.ForeignKeyConstraint(['ci_type_source_id'], ['ci_type.id'], ),
    sa.ForeignKeyConstraint(['ci_type_target_id'], ['ci_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci_type_source_id', 'ci_type_relation_id', 'ci_type_target_id'),
    comment='配置项类型与配置项类型关联'
    )
    op.create_table('ci_type_unique_index',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项类型唯一索引ID'),
    sa.Column('indexes', sa.JSON(), nullable=False, comment='配置项类型唯一索引数组'),
    sa.Column('ci_type_id', sa.BigInteger(), nullable=False, comment='配置项类型ID'),
    sa.ForeignKeyConstraint(['ci_type_id'], ['ci_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项类型唯一索引'
    )
    op.create_table('ci_cis',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项与配置项关联ID'),
    sa.Column('ci_source_id', sa.BigInteger(), nullable=True, comment='来源配置项ID'),
    sa.Column('ci_relation_id', sa.BigInteger(), nullable=True, comment='配置项与配合项关系ID'),
    sa.Column('ci_target_id', sa.BigInteger(), nullable=True, comment='目标配置项ID'),
    sa.ForeignKeyConstraint(['ci_relation_id'], ['relation.id'], ),
    sa.ForeignKeyConstraint(['ci_source_id'], ['ci.id'], ),
    sa.ForeignKeyConstraint(['ci_target_id'], ['ci.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项与配置项关联'
    )
    op.create_table('ci_type_attribute',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项类型属性ID'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='配置项类型属性编码'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='配置项类型属性名称'),
    sa.Column('order', sa.BigInteger(), nullable=False, comment='配置项类型属性排序'),
    sa.Column('value_type', sa.Enum('FLOAT', 'INT', 'DATE', 'TIME', 'TEXT', 'BOOL', 'USER', 'JSON', 'TEXTAREA', 'TIMEZONE', 'DATETIME', name='configitemtypeattributevaluetype'), nullable=False, comment='配置项类型属性值类型'),
    sa.Column('value_is_editable', sa.Boolean(), nullable=False, comment='配置项类型属性值是否可编辑?'),
    sa.Column('value_is_required', sa.Boolean(), nullable=False, comment='配置项类型属性值是否必填?'),
    sa.Column('value_is_password', sa.Boolean(), nullable=False, comment='配置项类型属性值是否密码?'),
    sa.Column('value_is_url_link', sa.Boolean(), nullable=False, comment='配置项类型属性值是否链接?'),
    sa.Column('value_re_patterns', sa.Text(), nullable=True, comment='配置项类型属性值正则校验表达式'),
    sa.Column('value_ge_limit_nu', sa.BigInteger(), nullable=True, comment='配置项类型属性值最小值'),
    sa.Column('value_le_limit_nu', sa.BigInteger(), nullable=True, comment='配置项类型属性值最大值'),
    sa.Column('tips', sa.Text(), nullable=False, comment='配置项类型属性提示'),
    sa.Column('ci_type_attribute_group_id', sa.BigInteger(), nullable=False, comment='配置项类型属性分组ID'),
    sa.ForeignKeyConstraint(['ci_type_attribute_group_id'], ['ci_type_attribute_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci_type_attribute_group_id', 'code'),
    sa.UniqueConstraint('ci_type_attribute_group_id', 'name'),
    comment='配置项类型属性'
    )
    op.create_index(op.f('ix_ci_type_attribute_code'), 'ci_type_attribute', ['code'], unique=False)
    op.create_table('ci_bool_value',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项布尔值ID'),
    sa.Column('value', sa.Boolean(), nullable=False, comment='配置项布尔值'),
    sa.Column('ci_id', sa.BigInteger(), nullable=False, comment='配置项ID'),
    sa.Column('ci_type_attribute_id', sa.BigInteger(), nullable=True, comment='配置项类型属性id'),
    sa.ForeignKeyConstraint(['ci_id'], ['ci.id'], ),
    sa.ForeignKeyConstraint(['ci_type_attribute_id'], ['ci_type_attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项布尔值'
    )
    op.create_table('ci_date_value',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项日期值ID'),
    sa.Column('value', sa.Date(), nullable=False, comment='配置项日期值'),
    sa.Column('ci_id', sa.BigInteger(), nullable=False, comment='配置项ID'),
    sa.Column('ci_type_attribute_id', sa.BigInteger(), nullable=True, comment='配置项类型属性id'),
    sa.ForeignKeyConstraint(['ci_id'], ['ci.id'], ),
    sa.ForeignKeyConstraint(['ci_type_attribute_id'], ['ci_type_attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项日期值'
    )
    op.create_table('ci_datetime_value',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项日期值ID'),
    sa.Column('value', sa.DateTime(), nullable=False, comment='配置项日期时间值'),
    sa.Column('ci_id', sa.BigInteger(), nullable=False, comment='配置项ID'),
    sa.Column('ci_type_attribute_id', sa.BigInteger(), nullable=True, comment='配置项类型属性id'),
    sa.ForeignKeyConstraint(['ci_id'], ['ci.id'], ),
    sa.ForeignKeyConstraint(['ci_type_attribute_id'], ['ci_type_attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项日期时间值'
    )
    op.create_table('ci_float_value',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项小数值ID'),
    sa.Column('value', sa.Float(), nullable=False, comment='配置项小数值'),
    sa.Column('ci_id', sa.BigInteger(), nullable=False, comment='配置项ID'),
    sa.Column('ci_type_attribute_id', sa.BigInteger(), nullable=True, comment='配置项类型属性id'),
    sa.ForeignKeyConstraint(['ci_id'], ['ci.id'], ),
    sa.ForeignKeyConstraint(['ci_type_attribute_id'], ['ci_type_attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项小数值'
    )
    op.create_table('ci_int_value',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项整数值ID'),
    sa.Column('value', sa.BigInteger(), nullable=False, comment='配置项整数值'),
    sa.Column('ci_id', sa.BigInteger(), nullable=False, comment='配置项ID'),
    sa.Column('ci_type_attribute_id', sa.BigInteger(), nullable=True, comment='配置项类型属性id'),
    sa.ForeignKeyConstraint(['ci_id'], ['ci.id'], ),
    sa.ForeignKeyConstraint(['ci_type_attribute_id'], ['ci_type_attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项整数值'
    )
    op.create_table('ci_json_value',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项JSON值ID'),
    sa.Column('value', sa.JSON(), nullable=False, comment='配置项JSON值'),
    sa.Column('ci_id', sa.BigInteger(), nullable=False, comment='配置项ID'),
    sa.Column('ci_type_attribute_id', sa.BigInteger(), nullable=True, comment='配置项类型属性id'),
    sa.ForeignKeyConstraint(['ci_id'], ['ci.id'], ),
    sa.ForeignKeyConstraint(['ci_type_attribute_id'], ['ci_type_attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项JSON值'
    )
    op.create_table('ci_text_value',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项文本值ID'),
    sa.Column('value', sa.String(length=254), nullable=False, comment='配置项文本值'),
    sa.Column('ci_id', sa.BigInteger(), nullable=False, comment='配置项ID'),
    sa.Column('ci_type_attribute_id', sa.BigInteger(), nullable=True, comment='配置项类型属性id'),
    sa.ForeignKeyConstraint(['ci_id'], ['ci.id'], ),
    sa.ForeignKeyConstraint(['ci_type_attribute_id'], ['ci_type_attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项文本值'
    )
    op.create_table('ci_textarea_value',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项文本值ID'),
    sa.Column('value', sa.Text(), nullable=False, comment='配置项文本值'),
    sa.Column('ci_id', sa.BigInteger(), nullable=False, comment='配置项ID'),
    sa.Column('ci_type_attribute_id', sa.BigInteger(), nullable=True, comment='配置项类型属性id'),
    sa.ForeignKeyConstraint(['ci_id'], ['ci.id'], ),
    sa.ForeignKeyConstraint(['ci_type_attribute_id'], ['ci_type_attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项文本值'
    )
    op.create_table('ci_time_value',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项时间值ID'),
    sa.Column('value', sa.Time(), nullable=False, comment='配置项时间值'),
    sa.Column('ci_id', sa.BigInteger(), nullable=False, comment='配置项ID'),
    sa.Column('ci_type_attribute_id', sa.BigInteger(), nullable=True, comment='配置项类型属性id'),
    sa.ForeignKeyConstraint(['ci_id'], ['ci.id'], ),
    sa.ForeignKeyConstraint(['ci_type_attribute_id'], ['ci_type_attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项时间值'
    )
    op.create_table('ci_timezone_value',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项时区值ID'),
    sa.Column('value', sa.String(length=50), nullable=False, comment='配置项时区值'),
    sa.Column('ci_id', sa.BigInteger(), nullable=False, comment='配置项ID'),
    sa.Column('ci_type_attribute_id', sa.BigInteger(), nullable=True, comment='配置项类型属性id'),
    sa.ForeignKeyConstraint(['ci_id'], ['ci.id'], ),
    sa.ForeignKeyConstraint(['ci_type_attribute_id'], ['ci_type_attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项时区值'
    )
    op.create_table('ci_user_value',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='配置项用户值ID'),
    sa.Column('value', sa.BigInteger(), nullable=False, comment='配置项用户值'),
    sa.Column('ci_id', sa.BigInteger(), nullable=False, comment='配置项ID'),
    sa.Column('ci_type_attribute_id', sa.BigInteger(), nullable=True, comment='配置项类型属性id'),
    sa.ForeignKeyConstraint(['ci_id'], ['ci.id'], ),
    sa.ForeignKeyConstraint(['ci_type_attribute_id'], ['ci_type_attribute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='配置项用户值'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ci_user_value')
    op.drop_table('ci_timezone_value')
    op.drop_table('ci_time_value')
    op.drop_table('ci_textarea_value')
    op.drop_table('ci_text_value')
    op.drop_table('ci_json_value')
    op.drop_table('ci_int_value')
    op.drop_table('ci_float_value')
    op.drop_table('ci_datetime_value')
    op.drop_table('ci_date_value')
    op.drop_table('ci_bool_value')
    op.drop_index(op.f('ix_ci_type_attribute_code'), table_name='ci_type_attribute')
    op.drop_table('ci_type_attribute')
    op.drop_table('ci_cis')
    op.drop_table('ci_type_unique_index')
    op.drop_table('ci_type_ci_types')
    op.drop_index(op.f('ix_ci_type_attribute_group_code'), table_name='ci_type_attribute_group')
    op.drop_table('ci_type_attribute_group')
    op.drop_table('ci')
    op.drop_index(op.f('ix_ci_type_code'), table_name='ci_type')
    op.drop_table('ci_type')
    op.drop_index(op.f('ix_relation_code'), table_name='relation')
    op.drop_table('relation')
    op.drop_index(op.f('ix_ci_type_group_code'), table_name='ci_type_group')
    op.drop_table('ci_type_group')
    # ### end Alembic commands ###
